# Generated by Django 4.2.1 on 2023-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniamal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('specie', models.CharField(max_length=100)),
                ('lifespan', models.IntegerField()),
            ],
        ),
    ]
