# Generated by Django 4.2.1 on 2023-06-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aniamal',
            new_name='Animal',
        ),
    ]
